server:
  port: 9000
spring:
  application:
    name: cloud-shop-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:davidLv/dh-cloud-shop.git
          passphrase: hilary
          search-paths: dh-cloud-shop-config-repo
          clone-on-start: true
          force-pull: true
        default-profile: dev
      profile: dev